chrome = {
  // "as","cs","ac","a","c"
  Q:["","<d>CloseChrome</d>","","",""],
  W:["","<d>CloseWindow</d>","","",""],
  E:["Evernote","eyedrop","","<d>Extension</d>",""],
  R:["RefMe","reloadAll","","",""],
  T:["TodoList","<d>RecoverTabs</d>","","Toby_Tab","<d>New_Tab</d>"],
  Y:["","","","",""],
  U:["","URL_Short_(Google)","","",""],
  I:["InstaPaper", "<d>Inspect_Window</d>", "", "FatkunImage_Download", "" ],
  O:["OneNote", "<d>Bookmark </d>", "", "", "" ],
  P:["Package_Tab", "PushBullet", "", "", "" ],
  A:["", "", "", "", "" ],
  S:["Scholar", "", "", "", "" ],
  D:["Drive_Google", "Download", "", "Download_Tab", "" ],
  F:["Feedly_Notifier", "Font_What", "", "", "" ],
  G:["Google", "<d>find</d>", "", "", "" ],
  H:["Highlight_Multiple", "", "", "", "" ],
  J:["", "<d>Console</d>", "", "", "" ],
  K:["", "", "", "", "" ],
  L:["", "", "", "", "" ],
  Z:["Zotero", "", "", "", "" ],
  X:["", "", "", "", "" ],
  C:["Calendar_Google", "<d>Source</d>", "", "", "" ],
  V:["", "", "", "", "" ],
  B:["", "<d>BookmarkBar</d>", "", "", "" ],
  N:["", "<d>IncognitoWindow</d>", "", "", "" ],
  M:["", "<d>MultiUser</d>", "", "Mute_Tab", "" ],
}

sublimetext={
  // "as","cs","ac","a","c"
  Q:[ "", "", "", "", "" ],
  W:[ "", "", "word_wrap", "", "" ],
  E:[ "", "", "", "", "" ],
  R:[ "", "", "browser_refresh", "", "" ],
  T:[ "", "<d>RecoverTab</d>", "Trail_space", "", "" ],
  Y:[ "", "", "", "", "" ],
  U:[ "", "", "", "", "" ],
  I:[ "", "", "", "", "" ],
  O:[ "", "", "Open_Dir", "", "" ],
  P:[ "", "<d>PackageControl</d>", "Workspace_select", "", "" ],
  A:[ "", "", "", "", "" ],
  S:[ "SimpleNote", "", "Sidebar_Reveal", "", "" ],
  D:[ "Dired_Category", "", "Date_add", "", "" ],
  F:[ "", "", "", "", "" ],
  G:[ "", "", "", "", "" ],
  H:[ "", "", "", "", "" ],
  J:[ "", "", "", "", "" ],
  K:[ "", "", "", "", "" ],
  L:[ "", "", "GroupChange", "", "" ],
  Z:[ "", "", "", "", "" ],
  X:[ "", "", "", "", "" ],
  C:[ "", "", "", "", "" ],
  V:[ "", "", "", "", "" ],
  B:[ "", "", "", "", "" ],
  N:[ "", "", "", "", "" ],
  M:[ "Markdown_Preview", "", "", "", "" ],
}

windows={
  Q:[ "", "", "", "", "" ],
  W:[ "Word_MicroSoft", "", "", "", "" ],
  E:[ "Email_Outlook", "", "", "", "" ],
  R:[ "", "", "", "", "" ],
  T:[ "", "", "", "", "" ],
  Y:[ "", "", "", "", "" ],
  U:[ "", "", "", "", "" ],
  I:[ "", "", "", "", "" ],
  O:[ "", "", "", "", "" ],
  P:[ "PowerPoint", "", "", "", "" ],
  A:[ "AutoScreen", "", "", "", "" ],
  S:[ "OneNote_ScreenShot", "SnipTool", "", "", "" ],
  D:[ "", "", "", "", "" ],
  F:[ "Foxit_PDF", "", "", "", "" ],
  G:[ "", "", "", "", "" ],
  H:[ "", "", "", "", "" ],
  J:[ "", "", "", "", "" ],
  K:[ "", "", "", "", "" ],
  L:[ "", "", "", "", "" ],
  Z:[ "Zotero", "", "", "", "" ],
  X:[ "", "", "", "", "" ],
  C:[ "CintaNote", "", "", "", "" ],
  V:[ "", "", "", "", "" ],
  B:[ "", "", "", "", "" ],
  N:[ "OneNote", "", "", "", "" ],
  M:[ "", "", "", "", "" ],
}